{
 "title": "BT-USD Exchange Rate",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "BT-USD Ex Rate LOW",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(local.exchange.rates, 'exchange rate')"
    }
   ]
  },
  {
   "title": "BT - USD Ex Rate HIGH",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(local.exchange.rates, 'exchange_rate')"
    }
   ]
  },
  {
   "title": "Dag Processing time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.airflow.dag_processing.last_runtime.myapp, 'dag processing time')"
    }
   ]
  },
  {
   "title": "Task duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "alias(stats.timers.airflow.dag.final_dag.task_get_exchange_rate.duration.count, 'duration-get ex rate')"
    },
    {
     "target": "alias(stats.timers.airflow.dag.final_dag.task_db_write.duration.count, 'duration-db write')"
    }
   ]
  }
 ]
}