{
 "title": "BT-USD Exchange Rate",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Status codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.response.200, 'response=200')"
    },
    {
     "target": "alias(stats.response.500, 'response=500')"
    }
   ]
  },
  {
   "title": "BT - USD Ex Rate HIGH",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(local.exchange.rates, 'exchange_rate')"
    }
   ]
  },
  {
   "title": "BT-USD Ex Rate LOW",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(local.exchange.rates, 'exchange rate')"
    }
   ]
  },
  {
   "title": "Dag Processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.airflow.dag_processing.last_runtime.myapp, 'dag processing time')"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "alias(stats.gauges.airflow.executor.running_tasks, 'Running tasks')"
    }
   ]
  },
  {
   "title": "Task duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "alias(stats.timers.airflow.dag.BT_USD_exchange.task_get_exchange_rate.duration.count, 'duration-get ex rate')"
    },
    {
     "target": "alias(stats.timers.airflow.dag.loading-duration.BT_USD_exchange.count, 'duration-db write')"
    }
   ]
  },
  {
   "title": "Scheduler Heartbeat",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "alias(stats.airflow.scheduler_heartbeat, 'heartbeat')"
    }
   ]
  },
  {
   "title": "Task Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats_counts.airflow.ti_successes, 'Task_sucess')"
    }
   ]
  },
  {
   "title": "Dag Import Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.airflow.dagbag_import_errors, 'Dag_import Errors')"
    }
   ]
  }
 ]
}